apiVersion: apps/v1
kind: Deployment
metadata:
  name: metastore
  labels:
    app: hive-metastore
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hive-metastore
  template:
    metadata:
      labels:
        app: hive-metastore
    spec:
      containers:
        - name: hive-metastore
          image: hive-metastore:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 9083
          env:
            - name: POSTGRES_CONNECTION_URL
              valueFrom:
                secretKeyRef:
                  name: hive-metastore-secrets
                  key: postgres-connection-url
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hive-metastore-secrets
                  key: postgres-password
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: hive-metastore-secrets
                  key: s3-key-id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: hive-metastore-secrets
                  key: s3-key-secret
            - name: AWS_REGION
              value: "us-east-1"